import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import '@/styles/tailwind.css'
import ThemeProvider from '@/components/layout/theme-provider'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'
import BackToTopButton from '@/components/common/back-to-top-buton'
import { I18nProvider } from '@/providers/i18n-provider'
// import '@/lib/i18n'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col justify-between">
              <Header />
              <main className="flex-1 min-h-screen">{children}</main>
              <Footer />
            </div>

            <BackToTopButton />
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  )
}
